Fabricator(:movie, aliases: ["Up"]) do
  title "Up"
  year "2009"
  rated "PG"
  released "29 May 2009"
  runtime "96 min"
  genre "Animation, Adventure, Drama"
  director "Pete Docter, Bob Peterson"
  writer "Pete Docter (story), Bob Peterson (story), Thomas McCarthy (story), Bob Peterson (screenplay), Pete Docter (screenplay)"
  actors "Edward Asner, Christopher Plummer, Jordan Nagai, Bob Peterson"
  plot "By tying thousands of balloons to his home, 78-year-old Carl sets out to fulfill his lifelong dream to see the wilds of South America. Russell, a wilderness explorer 70 years younger, inadvertently becomes a stowaway."
  poster "http://ia.media-imdb.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg"
  tomato_meter "98"
  tomato_image "certified"
  tomato_user_meter "89"
  dvd "10 Nov 2009"
  box_office "$293.0M"
  production "Walt Disney Pictures"
  tomato_reviews "278"
  tomato_fresh "273"
  tomato_rotten "5"
  tomato_user_reviews "1,190,300"
end

Fabricator(:movie, aliases: ["Gravity"]) do
  title "Gravity"
  year "2013"
  rated "PG-13"
  released "04 Oct 2013"
  runtime "91 min"
  genre "Drama, Sci-Fi, Thriller"
  director "Alfonso Cuarón"
  writer "Alfonso Cuarón, Jonás Cuarón"
  actors "Sandra Bullock, George Clooney, Ed Harris, Orto Ignatiussen"
  plot "A medical engineer and an astronaut work together to survive after an accident leaves them adrift in space."
  poster "http://ia.media-imdb.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_SX300.jpg"
  tomato_meter "97"
  tomato_image "certified"
  tomato_user_meter "84"
  dvd "25 Feb 2014"
  box_office "269.3M"
  production "Warner Bros. Pictures"
  tomato_reviews "299"
  tomato_fresh "290"
  tomato_rotten "9"
  tomato_user_reviews "231,339"
end

Fabricator(:movie, aliases: ["American Hustle"]) do
  title "American Hustle"
  year "2013"
  rated "R"
  released "20 Dec 2013"
  runtime "138 min"
  genre "Crime, Drama"
  director "David O. Russell"
  writer "Eric Warren Singer, David O. Russell"
  actors "Christian Bale, Bradley Cooper, Amy Adams, Jeremy Renner"
  plot "A con man, Irving Rosenfeld, along with his seductive British partner, Sydney Prosser, is forced to work for a wild FBI agent, Richie DiMaso. DiMaso pushes them into a world of Jersey powerbrokers and mafia."
  poster "http://ia.media-imdb.com/images/M/MV5BNjkxMTc0MDc4N15BMl5BanBnXkFtZTgwODUyNTI1MDE@._V1_SX300.jpg"
  tomato_meter "93"
  tomato_image "certified"
  tomato_user_meter "79"
  dvd "18 Mar 2014"
  box_office "$133.5M"
  production "Sony Pictures"
  tomato_reviews "240"
  tomato_fresh "223"
  tomato_rotten "17"
  tomato_user_reviews "114,982"
end
