Fabricator(:movie, aliases: ["Up"]) do
  title "Up"
  year "2009"
  rated "PG"
  released "29 May 2009"
  runtime "96 min"
  genre "Animation, Adventure, Drama"
  director "Pete Docter, Bob Peterson"
  writer "Pete Docter (story), Bob Peterson (story), Thomas McCarthy (story), Bob Peterson (screenplay), Pete Docter (screenplay)"
  actors "Edward Asner, Christopher Plummer, Jordan Nagai, Bob Peterson"
  plot "By tying thousands of balloons to his home, 78-year-old Carl sets out to fulfill his lifelong dream to see the wilds of South America. Russell, a wilderness explorer 70 years younger, inadvertently becomes a stowaway."
  poster "http://ia.media-imdb.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg"
  tomato_meter "98"
  tomato_image "certified"
  tomato_user_meter "89"
  dvd "10 Nov 2009"
  box_office "$293.0M"
  production "Walt Disney Pictures"
  tomato_reviews "278"
  tomato_fresh "273"
  tomato_rotten "5"
  tomato_user_reviews "1,190,300"
end